# This file was generated by GoReleaser. DO NOT EDIT.
cask "wakafetch" do
  name "wakafetch"
  desc "WakaTime activity fetcher CLI"
  homepage "https://github.com/b00y0h/wakafetch"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wakafetch"

  on_macos do
    on_intel do
      url "https://github.com/b00y0h/wakafetch/releases/download/v#{version}/wakafetch_#{version}_darwin_amd64.tar.gz"
      sha256 "606f5be52f663eae926c2549c45fb975b2d4837e2bc09ff729a1fb7321680a28"
    end
    on_arm do
      url "https://github.com/b00y0h/wakafetch/releases/download/v#{version}/wakafetch_#{version}_darwin_arm64.tar.gz"
      sha256 "ea5e7b6c6d6878d5281269aef9778d3c4a9357af5e3a8b3d5d564446b6af713c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/b00y0h/wakafetch/releases/download/v#{version}/wakafetch_#{version}_linux_amd64.tar.gz"
      sha256 "19767b2ffe933f6a3799645416880fc0a2be38921006b6bde0cc2fc8f5db8c62"
    end
    on_arm do
      url "https://github.com/b00y0h/wakafetch/releases/download/v#{version}/wakafetch_#{version}_linux_arm64.tar.gz"
      sha256 "8ffef310e1d688814c372bd064e512c52213fe54ce379dad84a83726ba650456"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wakafetch"]
    end
  end

  # No zap stanza required
end
